apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-test-cluster
  annotations:
    github.com/project-slug: fernando-bercedo-NTT/skills-publish-packages
  description: AWS EKS cluster managed by Terraform
  tags:
    - aws
    - eks
    - terraform
spec:
  type: service
  lifecycle: experimental
  owner: guests
